#!/usr/bin/python3

print ('Starting garage door server')

from gpiozero import OutputDevice
from http import HTTPStatus
from http.server import HTTPServer, BaseHTTPRequestHandler
from time import sleep

HTTP_PORT   = 80
RELAY_PIN   = 4
RELAY_DELAY = 0.3

root_html = open ('root.html').read ()
button_data = open ('button.png', 'rb').read ()

device = OutputDevice (RELAY_PIN, active_high = False)

def toggle_relay ():
    device.on ()
    sleep (RELAY_DELAY)
    device.off ()

class GarageDoorHandler (BaseHTTPRequestHandler):
    def do_GET (self):
        if self.path == '/':
            self.send_response (HTTPStatus.OK)
            self.send_header ('Content-type', 'text/html')
            self.end_headers ()
            self.wfile.write (bytes (root_html, 'UTF-8'))
        elif self.path == '/button.png':
            self.send_response (HTTPStatus.OK)
            self.send_header ('Content-type', 'image/png')
            self.end_headers ()
            self.wfile.write (button_data)
        elif self.path == '/press-button':
            self.send_response (HTTPStatus.OK)
            self.end_headers ()
        else:
            self.send_response (HTTPStatus.NOT_FOUND)
            self.end_headers ()

s = HTTPServer (('', HTTP_PORT), GarageDoorHandler)

print ('Ready to serve')
s.serve_forever ()
