#!/usr/bin/python3

print ('Starting garage door server')

import RPi.GPIO as GPIO
from http import HTTPStatus
from http.server import HTTPServer, BaseHTTPRequestHandler
from time import sleep

HTTP_PORT   = 80
RELAY_PIN   = 4
RELAY_DELAY = 0.3

root_html = open ('root.html').read ()
button_data = open ('button.png', 'rb').read ()

GPIO.setmode (GPIO.BCM)
GPIO.setup (RELAY_PIN, GPIO.OUT, initial = GPIO.HIGH)

def toggle_relay ():
    GPIO.output (RELAY_PIN, GPIO.LOW)
    sleep (RELAY_DELAY)
    GPIO.output (RELAY_PIN, GPIO.HIGH)

class GarageDoorHandler (BaseHTTPRequestHandler):
    def do_GET (self):
        if self.path == '/':
            self.send_response (HTTPStatus.OK)
            self.send_header ('Content-type', 'text/html')
            self.end_headers ()
            self.wfile.write (bytes (root_html, 'UTF-8'))
        elif self.path == '/button.png':
            self.send_response (HTTPStatus.OK)
            self.send_header ('Content-type', 'image/png')
            self.end_headers ()
            self.wfile.write (button_data)
        elif self.path == '/press-button':
            toggle_relay ()
            self.send_response (HTTPStatus.OK)
            self.end_headers ()
        else:
            self.send_response (HTTPStatus.NOT_FOUND)
            self.end_headers ()

s = HTTPServer (('', HTTP_PORT), GarageDoorHandler)

print ('Ready to serve')
s.serve_forever ()
