#!/usr/bin/python3

print ('Starting garage door server')

from http import HTTPStatus
from http.server import HTTPServer, BaseHTTPRequestHandler
from os import environ
from time import sleep

HTTP_PORT   = 80
RELAY_DELAY = 0.3
DEVICE = '/sys/class/gpio/gpio4'
DATA_PATH = environ['SNAP']

root_html = open (DATA_PATH + '/root.html').read ()
button_data = open (DATA_PATH + '/button.png', 'rb').read ()

def write_device (name, value):
    open (DEVICE + '/' + name, 'w').write (value)

write_device ('active_low', '1');
write_device ('direction', 'out')

def toggle_relay ():
    write_device ('value', '1')
    sleep (RELAY_DELAY)
    write_device ('value', '0')

class GarageDoorHandler (BaseHTTPRequestHandler):
    def do_GET (self):
        if self.path == '/':
            self.send_response (HTTPStatus.OK)
            self.send_header ('Content-type', 'text/html')
            self.end_headers ()
            self.wfile.write (bytes (root_html, 'UTF-8'))
        elif self.path == '/button.png':
            self.send_response (HTTPStatus.OK)
            self.send_header ('Content-type', 'image/png')
            self.end_headers ()
            self.wfile.write (button_data)
        elif self.path == '/press-button':
            toggle_relay ()
            self.send_response (HTTPStatus.OK)
            self.end_headers ()
        else:
            self.send_response (HTTPStatus.NOT_FOUND)
            self.end_headers ()

s = HTTPServer (('', HTTP_PORT), GarageDoorHandler)

print ('Ready to serve')
s.serve_forever ()
