name: garage-door
base: core18
version: git
version-script: |
  echo $(date --utc +%Y%m%d).$(git rev-parse HEAD | cut -c -7)
summary: Garage Door web server for Raspberry Pi
description: |
  Runs a simple web server that exposes a button to control a garage door motor via a relay.
  Runs on a Raspberry Pi (A+ model recommended).

architectures:
  - build-on: armhf
    run-on: armhf

grade: stable
confinement: strict

parts:
  garage-door-deps:
    plugin: python
    python-version: python3
    python-packages:
      - gpiozero
      - RPi.GPIO
  garage-door:
    plugin: dump
    source: .
    stage:
      - button.png
      - garage-door-server
      - root.html

apps:
  garage-door-server:
    daemon: simple
    command: garage-door-server
    plugs:
      - bcm-gpio-0
      - bcm-gpio-1
      - bcm-gpio-2
      - bcm-gpio-3
      - bcm-gpio-4
      - bcm-gpio-5
      - bcm-gpio-6
      - bcm-gpio-7
      - bcm-gpio-8
      - bcm-gpio-9
      - bcm-gpio-10
      - bcm-gpio-11
      - bcm-gpio-12
      - bcm-gpio-13
      - bcm-gpio-14
      - bcm-gpio-15
      - bcm-gpio-16
      - bcm-gpio-17
      - bcm-gpio-18
      - bcm-gpio-19
      - bcm-gpio-20
      - bcm-gpio-21
      - bcm-gpio-22
      - bcm-gpio-23
      - bcm-gpio-24
      - bcm-gpio-25
      - bcm-gpio-26
      - bcm-gpio-27
    environment:
      PYTHONPATH: $SNAP/lib/python3.6/site-packages
