name: garage-door
base: core18
version: git
version-script: |
  echo $(date --utc +%Y%m%d).$(git rev-parse HEAD | cut -c -7)
summary: Garage Door web server for Raspberry Pi
description: |
  Runs a simple web server that exposes a button to control a garage door motor via a relay.
  Runs on a Raspberry Pi (A+ model recommended).

architectures:
  - build-on: armhf
    run-on: armhf

grade: stable
confinement: strict

parts:
  garage-door-deps:
    plugin: python
    python-version: python3
    python-packages:
      - gpiozero
      - RPi.GPIO
  garage-door:
    plugin: dump
    source: .
    stage:
      - button.png
      - garage-door-server
      - root.html

apps:
  garage-door-server:
    daemon: simple
    command: garage-door-server
    plugs: [ gpio ]
    environment:
      PYTHONPATH: $SNAP/lib/python3.6/site-packages
